### PR TITLE
Update sample data script

### PR DESCRIPTION
**Pull request by brittballard**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/bb-sample-data">analyzed this pull request</a>.

**Comment by brittballard** [comment]
Actually, this isn't ready for review/merge. I need to change one more thing real quick.

**Comment by brittballard** [comment]
Now, it's ready for review.

https://github.com/projectjellyfish/api/issues/318

**Comment by stackus** [comment]
:+1:

**Pull request merged**
