### PR TITLE
Serve Angular app from Rails

### LINKED ISSUE #358: Serve ux angular app from Rails (combining repos)
- [x] Can't view Admin items
- [x] No background images
- [x] Can't fill in other than 0 on new project form

### PR DESCRIPTION
**Pull request by calebthompson**
Resolves #358

### CODE REVIEW

**Comment by calebthompson** [comment]
https://github.com/projectjellyfish/api/compare/934cc70...combine is slightly easier to take a look at, but is still too large for GitHub.

**Comment by chriskacerguis** [comment]
Can't auto-merge...

**Comment by calebthompson** [comment]
Yeah I reverted the merge of master into this to make it simpler to review. I'll manually merge once this gets the thumbs-up.

**Comment by stackus** [comment]
This got a verbal thumbs-up to merge I'm guessing?

**Comment by calebthompson** [comment]
Yeah Chris came over.

**Pull request merged**
