### PR TITLE
Bug/ux 504 date validation edit project form

### PR DESCRIPTION
**Pull request by sonejah21**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@sonejah21 could you take a look at the build and let me know?  I think that @calebthompson and @masonforest where working on a fix for the project issue...so you may need to merge their changes in once they are done.

**Comment by sonejah21** [comment]
Sounds good, @chriskacerguis - thanks!

**Comment by masonforest** [comment]
This looks like a separate issue. Our test was filling in a start date that was [before today](https://github.com/projectjellyfish/api/blob/master/spec/features/create_a_project_spec.rb#L14). [This commit](https://github.com/projectjellyfish/api/commit/3ddc1078b10afc8b9c7d0a3db5eb4cafe59ab7d1) should fix it. :panda_face:

**Comment by sonejah21** [comment]
Looks like this one is good to go if you'd like to merge it in, @chriskacerguis - I tested the date validation and it works great with the commits Mason made yesterday :)

**Pull request merged**
