### PR TITLE
Readded password and status_msg to order_items table.

### PR DESCRIPTION
**Pull request by OBCENEIKON**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/feature/JEL-277-Update_order_items_table">analyzed this pull request</a>.

**Comment by stackus** [comment]
I don't see any migrations tied to these changes.

**Comment by chriskacerguis** [comment]
What's password for?

**Comment by jntullo** [comment]
When creating an RDS instance, the password is never passed back once you set it. So, we need a place to store it.

**Comment by chriskacerguis** [comment]
@jntullo Wouldn't that be stored in the "provider_response" JSON column?

**Comment by chriskacerguis** [comment]
@OBCENEIKON aren't we getting rid of the order_derivations table?  Looks like it's still here?

**Comment by jntullo** [comment]
@chriskacerguis no, it doesn't get passed back in the response, it's a write-only property

**Pull request merged**
