### PR TITLE
updated to postgresql 9.4

### PR DESCRIPTION
**Pull request by chriskacerguis**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/feature/api-289-postgresql-update-9-4">analyzed this pull request</a>.

**Comment by stackus** [comment]
This is specifically to 9.4.1 or 9.4 is OK too?

**Comment by chriskacerguis** [comment]
Travis will grab the latest patch release for 9.4 (so yes, 9.4.1 is good...and Travis will use that)

**Comment by chriskacerguis** [comment]
Resolves https://github.com/projectjellyfish/api/issues/289

**Pull request merged**
