### PR TITLE
Remove api.constants.js

### PR DESCRIPTION
**Pull request by masonforest**
As discussed [here](https://github.com/projectjellyfish/api/pull/670#discussion_r31290151).

### CODE REVIEW

**Comment by calebthompson** [comment]
Tests aren't passing on this branch, so while the change looks fine I don't know whether it works or anything. LGTM I guess?

**Comment by chriskacerguis** [comment]
@masonforest Can you take a look at this tests to see what's up?

**Comment by masonforest** [comment]
Yep! This is the same thing as the other PR. This is branched off `enhancement/JEL_#601-Integrate-CM-UX-into-Jellyfis-UX` which is failing so this branch will fail as well. Next I'll work on passing the tests on `enhancement/JEL_#601-Integrate-CM-UX-into-Jellyfis-UX` so we can be confident everything is working in the new UX.

**Comment by calebthompson** [comment]
Rebased & fixed failures related to my tags changes, but there's some strange failures you'll probably have to look into @masonforest

**Comment by chriskacerguis** [comment]
lgtm

**Pull request merged**
