### PR TITLE
Bug/fix gemfile lock

### PR DESCRIPTION
**Pull request by mafernando**
rebuilt gemfile lock

### CODE REVIEW

**Comment by chriskacerguis** [comment]
what happened to the gemfile?

**Comment by AllenBW** [comment]
wooh! passing success!

**Comment by stackus** [comment]
Looks like it removes ming32 (windows) gem references and updates a few supporting gems. Only see bumps to the minor or patch versions to breakages should be minimal to none.

Looks fine to me.

**Comment by AllenBW** [comment]
this one is on me, i accidentally committed my gemfile, @mafernando was kind enough to expeditiously rectify my error

**Pull request merged**
