### PR TITLE
Enhancement/393 dashboard to be more dashboard like

### PR DESCRIPTION
**Pull request by AllenBW**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW Looks like I can't auto merge...can you update and try again?

**Comment by AllenBW** [comment]
yep, on that now!

**Comment by chriskacerguis** [comment]
@AllenBW looks like there is a problem with your Gemfile

**Comment by AllenBW** [comment]
totally on top of it!

**Comment by AllenBW** [comment]
and we are great to merge!

**Pull request merged**
