### PR TITLE
Feature/jel 277 order items

### PR DESCRIPTION
**Pull request by jntullo**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/feature/jel_277_order_items">analyzed this pull request</a>.

**Comment by stackus** [comment]
The `provision_worker.rb` file had all of my changes reverted. Could you please make sure those get put back.

Primarily the changes used the new hid column for settings lookup. Using names is going problematic, they could change at any time, and the column is not indexed.

**Comment by chriskacerguis** [comment]
@stackus this didn't get merged.  Could you clarify the issue?

**Comment by stackus** [comment]
Already spoke with @chriskacerguis but I'll respond here too so there is a paper trail here as well.

I saw a merge with master and assumed it contained my changes. Everything is fine, it was a bad assumption. Carry on!

**Pull request closed without merging**
