### PR TITLE
Fix product type tags

### PR DESCRIPTION
**Pull request by calebthompson**
* Revert original `/categories` endpoint and subsequent temporary fixes
* Include tags in product_types endpoint

### CODE REVIEW

**Comment by calebthompson** [comment]
@AllenBW @OBCENEIKON

**Comment by AllenBW** [comment]
AWESOME

**Comment by OBCENEIKON** [comment]
:jellythumb:

**Comment by AllenBW** [comment]
ok going to do it, can't wait.

**Comment by calebthompson** [comment]
Cool, was at lunch.

**Pull request merged**
