### PR TITLE
Refactor products to use polymorphic relationships

### PR DESCRIPTION
**Pull request by brittballard**
* Broke out manage_iq_products
* Broke out team_member_products
* Moved provisioning logic into product
* Added test coverage

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/bb-product-mods">analyzed this pull request</a>.

**Comment by brittballard** [comment]
I'll look at that failed Travis build.

**Comment by brittballard** [comment]
https://github.com/projectjellyfish/ux/pull/250

**Comment by brittballard** [comment]
Looks like you guys prefer a few different styles than we do. Fixing now.

**Comment by brittballard** [comment]
There are is an example of a spec in this PR as well. This will also get us some test coverage around order items.

**Comment by calebthompson** [comment]
This LGTM. @stackus or anyone else?

**Comment by chriskacerguis** [comment]
:+1: for me

**Comment by chriskacerguis** [comment]
@jntullo ?

**Comment by stackus** [comment]
Yeah I looked it over this morning. :+1: There might be a gremlin in there but I don't see it.

**Pull request merged**
