### PR TITLE
Enhancement/681 documentation routing

### PR DESCRIPTION
**Pull request by sonejah21**
Added in:
- System Requirements file
- INSTALL-OSX file
- INSTALL-RHEL file

These are needed to link properly from the landing page/ README file.

### CODE REVIEW

**Comment by calebthompson** [comment]
Should these be removed from the root of the project instead of copied?

**Comment by sonejah21** [comment]
Since they currently live on the Wiki page in Github - which hasn't been moved over yet to the ReadtheDocs (via the /docs folder) - I left them in the Wiki for the time being. Once the Wiki pages are moved into a nested format in RTD then I was going to remove them all from the Wiki. 

A dumb question though: does the Wiki of a repo live hidden in the root of a project? I thought those files lived on the Github GUI alone.

**Comment by calebthompson** [comment]
The two install files aren't: https://github.com/projectjellyfish/api/blob/master/INSTALL-OSX.md and https://github.com/projectjellyfish/api/blob/master/INSTALL-RHEL.md

**Comment by sonejah21** [comment]
Fixed :+1: The two install files were removed from root.

**Comment by calebthompson** [comment]
:+1:

**Pull request merged**
