### PR TITLE
Update to Ruby 2.2.1

### PR DESCRIPTION
**Pull request by calebthompson**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/54d4fa64695680762a0024c5/compare/2.2.1">analyzed this pull request</a>.

**Comment by calebthompson** [comment]
Changed the version numbers just to see whether there are any issues.

**Comment by calebthompson** [comment]
@stackus this okay with you or do you want to wait?

**Comment by stackus** [comment]
Looks like it'll be a safe upgrade. No issues from me.

**Pull request merged**
