### PR TITLE
Add initial feature specs

### PR DESCRIPTION
**Pull request by masonforest**

### CODE REVIEW

**Comment by calebthompson** [comment]
@jntullo @sonejah21 @mafernando It begins! Please please ask any questions you have on these new specs. We're happy to help you write your first couple if needed.

**Comment by jntullo** [comment]
@calebthompson woah this looks great. Thanks!

**Comment by chriskacerguis** [comment]
Can't auto-merge.  @masonforest can you take a look?

**Comment by masonforest** [comment]
Rebased. Should be good to auto-merge

**Pull request merged**
