### PR TITLE
Feature/remove admin settings

### PR DESCRIPTION
**Pull request by mafernando**
Removed references to old admin settings table.
Using Dotenv for these values.

### CODE REVIEW

**Comment by stackus** [comment]
You'll also want to also drop `setting_fields` from the schema, right?

**Comment by mafernando** [comment]
@stackus - I believe you are correct, will update this PR before merging. Thanks.

**Comment by mafernando** [comment]
Closing this because it broke `rake sample:demo`

**Comment by mafernando** [comment]
sorry for the noise, recreated this branch from scratch [here](https://github.com/projectjellyfish/api/pull/511)

**Pull request closed without merging**
